---
ssh_keys:
  christoph:
    manjaro: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIClxV0vgGL8Itprdt2gpgjREpdx8+uPhZVb9i49ksMYC christoph@manjaro
    Christoph-XPS: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDRHH+H66LM5L3PlfnuyjOQZEBWBSJUrcXXivhMvAXoz chris@Christoph-XPS

admins:
  - christoph

sshd:
  AuthenticationMethods: "publickey"
  Ciphers: "chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr"
  KexAlgorithms: "curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256"
  MACs: "hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com"
  PasswordAuthentication: "no"
  PermitRootLogin: "prohibit-password"


